name: ci
on:
  pull_request:
      branches:
        - "main"
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    container:
      image: ocaml/opam:alpine-ocaml-5.0@sha256:3ddad7dfb7321d086f7be0fa3807630a8eeb098a5ff7ddfb3d28fc3c853559bf
      options: --user root
    steps:
      - name: Install external deps
        run: sudo apk add --update cmake libffi-dev linux-headers zlib-dev
      - name: Clone Custom Events PR
        run: git clone https://github.com/TheLortex/ocaml && git -C ./ocaml checkout 61f10168da60e94a5f9c2d1ce4cc4e4d512d0007
      - name: Build compiler
        run: cd ocaml && opam switch create --empty custom-events && opam pin add ocaml-variants.5.1.0+custom-events . -y
        env:
          OPAMROOT: /home/opam/.opam
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Meio Deps 🐈‍⬛
        run: opam pin . -yn && opam install . --deps-only --with-test
        env:
          OPAMROOT: /home/opam/.opam
      - name: Build
        run: opam exec -- dune build
        env:
          OPAMROOT: /home/opam/.opam
